## =========================================================
## 06_OPLSDA.R
## Robust OPLS-DA and VIP outputs
## v29:
##   - ropls success: true OPLS-DA model + VIP + diagnostic plot
##   - ropls failure: fallback VIP-like score + VIP plot
##   - always writes per-comparison files into results/oplsda/
## =========================================================

source("config/config.R")
source("functions/utils/common_utils.R")
source("functions/stats/run_oplsda.R")
source("functions/plots/save_plot.R")
source("functions/plots/plot_vip.R")

data02 <- readRDS(file.path(dir_rds, "02_preprocessed.rds"))
comparisons <- readRDS(file.path(dir_rds, "04_comparisons.rds"))

limma_results_file <- file.path(dir_rds, "05_limma_results.rds")
limma_results <- if (file.exists(limma_results_file)) readRDS(limma_results_file) else list()

format_comparison_title <- function(comp_row) {
  ## Use the exact comparison name as figure title, e.g. M03_48h_Fg_vs_CK
  if ("comparison" %in% colnames(comp_row)) {
    nm <- as.character(comp_row$comparison)
    if (!is.na(nm) && nm != "") return(nm)
  }

  genotype <- if ("genotype" %in% colnames(comp_row)) as.character(comp_row$genotype) else NA_character_
  time <- if ("time" %in% colnames(comp_row)) as.character(comp_row$time) else NA_character_
  case_treat <- if ("case_treatment" %in% colnames(comp_row)) as.character(comp_row$case_treatment) else NA_character_
  control_treat <- if ("control_treatment" %in% colnames(comp_row)) as.character(comp_row$control_treatment) else NA_character_

  parts <- c(genotype, time, case_treat, "vs", control_treat)
  parts <- parts[!is.na(parts) & parts != ""]
  paste(parts, collapse = "_")
}

opls_results <- list()
vip_tables <- list()
summary_tables <- list()

dir.create(dir_oplsda, recursive = TRUE, showWarnings = FALSE)

## Clean only old top-level index outputs generated by this script. Do not delete user files.
old_index_files <- file.path(
  dir_oplsda,
  c("OPLSDA_output_index.xlsx", "OPLSDA_summary_all.xlsx")
)
suppressWarnings(file.remove(old_index_files[file.exists(old_index_files)]))

if (!isTRUE(run_oplsda)) {
  message("OPLS-DA disabled in config. Empty OPLS-DA outputs will be saved.")
  summary_tables[["disabled"]] <- data.frame(
    comparison = NA_character_,
    status = "disabled",
    message = "run_oplsda is FALSE in config.R",
    stringsAsFactors = FALSE
  )
} else {
  for (i in seq_len(nrow(comparisons))) {
    comp <- comparisons[i, ]
    nm <- comp$comparison
    title_txt <- format_comparison_title(comp)
    safe_nm <- safe_filename(nm)

    message("Running OPLS-DA/VIP: ", nm)

    out_dir <- file.path(dir_oplsda, safe_nm)
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

    opls_res <- tryCatch(
      run_oplsda_single(
        expr_scaled = data02$expr_scaled,
        sample_info = data02$sample_info,
        case_group = comp$case_group,
        control_group = comp$control_group,
        permI = opls_permI,
        fallback = TRUE
      ),
      error = function(e) {
        warning("OPLS-DA/VIP failed for ", nm, ": ", e$message)
        list(
          model = NULL,
          vip = NULL,
          summary = data.frame(
            comparison = nm,
            status = "failed",
            message = e$message,
            stringsAsFactors = FALSE
          ),
          status = "failed",
          message = e$message
        )
      }
    )

    opls_results[[nm]] <- opls_res

    summary_df <- if (!is.null(opls_res$summary)) {
      as.data.frame(opls_res$summary, check.names = FALSE)
    } else {
      data.frame(
        comparison = nm,
        status = ifelse(is.null(opls_res$model), "no_model", "model_available"),
        message = ifelse(is.null(opls_res$message), NA_character_, as.character(opls_res$message)),
        stringsAsFactors = FALSE
      )
    }

    summary_df$comparison <- nm
    summary_df$title <- title_txt
    summary_df$output_folder <- out_dir
    summary_tables[[nm]] <- summary_df

    vip_df <- NULL
    if (!is.null(opls_res$vip) && nrow(opls_res$vip) > 0) {
      vip_df <- as.data.frame(opls_res$vip, check.names = FALSE)
      vip_df$comparison <- nm
      vip_df$title <- title_txt
      vip_tables[[nm]] <- vip_df
    }

    ## Always write per-comparison summary/VIP information into results/oplsda/<comparison>/
    if (requireNamespace("openxlsx", quietly = TRUE)) {
      write_xlsx_list(
        list(
          OPLSDA_summary = summary_df,
          VIP = if (!is.null(vip_df)) vip_df else data.frame(),
          note = data.frame(
            item = c(
              "model_status",
              "VIP_method",
              "output_folder",
              "why_ropls_plot_may_be_absent"
            ),
            value = c(
              ifelse(is.null(opls_res$model), "No ropls model object; fallback or failed run", "ropls model object available"),
              if (!is.null(vip_df) && "VIP_method" %in% colnames(vip_df)) paste(unique(vip_df$VIP_method), collapse = "; ") else NA_character_,
              out_dir,
              "ropls diagnostic plots are only generated when ropls successfully returns a model"
            ),
            stringsAsFactors = FALSE
          )
        ),
        file.path(out_dir, paste0(safe_nm, "_OPLSDA_VIP_summary.xlsx"))
      )
    }

    ## Also write CSV files for quick inspection without Excel.
    utils::write.csv(
      summary_df,
      file = file.path(out_dir, paste0(safe_nm, "_OPLSDA_summary.csv")),
      row.names = FALSE
    )
    if (!is.null(vip_df) && nrow(vip_df) > 0) {
      utils::write.csv(
        vip_df,
        file = file.path(out_dir, paste0(safe_nm, "_VIP.csv")),
        row.names = FALSE
      )
    }

    ## Save VIP bar plot even when OPLS-DA fell back to VIP-like ranking.
    if (!is.null(vip_df) && nrow(vip_df) > 0) {
      res_for_vip <- if (length(limma_results) > 0 && nm %in% names(limma_results)) limma_results[[nm]] else NULL

      p_vip <- tryCatch({
        plot_vip(
          vip_df = vip_df,
          annotation = data02$annotation,
          res = res_for_vip,
          top_n = vip_standalone_top_n,
          focus_classes = focus_classes,
          focus_bx_patterns = focus_bx_patterns,
          focus_only = FALSE,
          sig_only = FALSE,
          stat_col = volcano_stat_col,
          pvalue_cutoff = pvalue_cutoff,
          logFC_cutoff = logFC_cutoff,
          title = paste0(title_txt, "_VIP_score"),
          base_size = base_font_size,
          base_family = base_font_family
        )
      }, error = function(e) {
        warning("VIP plot failed for ", nm, ": ", e$message)
        NULL
      })

      if (!is.null(p_vip)) {
        tryCatch({
          save_ggplot_multi(
            p = p_vip,
            filename_prefix = file.path(out_dir, paste0(safe_nm, "_VIP_plot")),
            width = vip_width,
            height = vip_height,
            dpi = plot_dpi
          )
        }, error = function(e) {
          warning("Saving VIP plot failed for ", nm, ": ", e$message)
        })
      }
    } else {
      warning("No VIP table generated for ", nm)
    }

    ## Save ropls diagnostic plot only when a real ropls model exists.
    if (!is.null(opls_res$model)) {
      tryCatch({
        grDevices::cairo_pdf(
          file.path(out_dir, paste0(safe_nm, "_ropls_diagnostic_plots.pdf")),
          width = 8,
          height = 6
        )
        try(plot(opls_res$model), silent = TRUE)
        grDevices::dev.off()
      }, error = function(e) {
        warning("ropls diagnostic plot failed for ", nm, ": ", e$message)
        try(grDevices::dev.off(), silent = TRUE)
      })
    } else {
      ## Write a small note so the folder is self-explanatory.
      writeLines(
        c(
          paste0("Comparison: ", nm),
          paste0("Title: ", title_txt),
          "No ropls diagnostic plot was generated because no ropls model object was returned.",
          "This usually means ropls is not installed, model fitting failed, or fallback VIP-like ranking was used.",
          "Check the *_OPLSDA_VIP_summary.xlsx file in this folder."
        ),
        con = file.path(out_dir, paste0(safe_nm, "_NO_ropls_model_note.txt"))
      )
    }
  }
}

saveRDS(opls_results, file.path(dir_rds, "06_oplsda_results.rds"))

opls_summary_all <- dplyr::bind_rows(summary_tables)
vip_all <- dplyr::bind_rows(vip_tables)

write_xlsx_list(
  list(
    OPLSDA_summary = opls_summary_all,
    VIP = vip_all
  ),
  file.path(dir_tables, "06_OPLSDA_output.xlsx")
)

## Also write an index under results/oplsda/
if (requireNamespace("openxlsx", quietly = TRUE)) {
  comp_dirs <- list.dirs(dir_oplsda, recursive = FALSE, full.names = TRUE)
  output_index <- do.call(
    rbind,
    lapply(comp_dirs, function(d) {
      data.frame(
        folder = d,
        file = list.files(d, full.names = FALSE),
        stringsAsFactors = FALSE
      )
    })
  )

  write_xlsx_list(
    list(
      OPLSDA_summary = opls_summary_all,
      output_index = output_index
    ),
    file.path(dir_oplsda, "OPLSDA_output_index.xlsx")
  )
}

message("06_OPLSDA finished.")
message("VIP rows: ", nrow(vip_all))
message("OPLS-DA/VIP files are in: ", dir_oplsda)
